version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chat_backend_postgres
    environment:
      # Create postgres superuser (required by PostgreSQL)
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_admin_password
      # Also create our app database
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: chat_backend_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
