"""Initial schema

Revision ID: 793e27aceba8
Revises: 
Create Date: 2025-07-06 20:12:12.344050

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '793e27aceba8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'last_activity_at')
    op.drop_column('emotions', 'intensity')
    op.drop_column('emotions', 'emotion_metadata')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotions', sa.Column('emotion_metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.add_column('emotions', sa.Column('intensity', sa.REAL(), server_default=sa.text('0.5'), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), sa.Computed('COALESCE(updated_at, created_at)', persisted=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
