"""Initial schema

Revision ID: a435ed6c8db4
Revises:
Create Date: 2025-07-23 18:14:23.395261

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a435ed6c8db4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('total_chats', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('voice_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_last_activity', 'users', ['last_activity'], unique=False)
    op.create_index('idx_user_reset_token', 'users', ['reset_token'], unique=False)
    op.create_index('idx_user_username_active', 'users', ['username', 'is_active'], unique=False)
    op.create_index('idx_user_verification', 'users', ['verification_token'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_user_messages', sa.Integer(), nullable=False),
    sa.Column('total_ai_messages', sa.Integer(), nullable=False),
    sa.Column('chat_metadata', sa.JSON(), nullable=False),
    sa.Column('context_window_size', sa.Integer(), nullable=False),
    sa.Column('auto_title_generation', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_topic', sa.String(length=50), nullable=True),
    sa.Column('chat_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_chat_archived', 'chats', ['is_archived'], unique=False)
    op.create_index('idx_chat_deleted', 'chats', ['is_deleted'], unique=False)
    op.create_index('idx_chat_favorite', 'chats', ['is_favorite'], unique=False)
    op.create_index('idx_chat_last_message', 'chats', ['last_message_at'], unique=False)
    op.create_index('idx_chat_session', 'chats', ['session_id'], unique=False)
    op.create_index('idx_chat_user_active', 'chats', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_chat_user_created', 'chats', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_index(op.f('ix_chats_related_topic'), 'chats', ['related_topic'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('interaction_patterns', sa.JSON(), nullable=False),
    sa.Column('learning_data', sa.JSON(), nullable=False),
    sa.Column('features_enabled', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_preference_interaction', 'user_preferences', ['last_interaction_at'], unique=False)
    op.create_index('idx_user_preference_updated', 'user_preferences', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'FILE', 'AUDIO', 'VIDEO', 'SYSTEM', 'ERROR', name='messagetype'), nullable=False),
    sa.Column('sender_type', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='sendertype'), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('emotion_detected', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_message_deleted', 'messages', ['is_deleted'], unique=False)
    op.create_index('idx_message_emotion', 'messages', ['emotion_detected'], unique=False)
    op.create_index('idx_message_flagged', 'messages', ['is_flagged'], unique=False)
    op.create_index('idx_message_hash', 'messages', ['content_hash'], unique=False)
    op.create_index('idx_message_sender_type', 'messages', ['sender_type'], unique=False)
    op.create_index('idx_message_type', 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_content_hash'), 'messages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('primary_emotion', sa.Enum('JOY', 'SADNESS', 'ANGER', 'FEAR', 'SURPRISE', 'DISGUST', 'CONTEMPT', 'NEUTRAL', 'EXCITEMENT', 'ANXIETY', 'FRUSTRATION', 'CONTENTMENT', name='emotiontype'), nullable=False),
    sa.Column('secondary_emotion', sa.Enum('JOY', 'SADNESS', 'ANGER', 'FEAR', 'SURPRISE', 'DISGUST', 'CONTEMPT', 'NEUTRAL', 'EXCITEMENT', 'ANXIETY', 'FRUSTRATION', 'CONTENTMENT', name='emotiontype'), nullable=True),
    sa.Column('emotion_scores', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('analysis_method', sa.String(length=50), nullable=False),
    sa.Column('text_analyzed', sa.Text(), nullable=True),
    sa.Column('context_used', sa.JSON(), nullable=False),
    sa.Column('emotion_intensity', sa.Float(), nullable=False),
    sa.Column('emotion_duration', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emotion_chat', 'emotions', ['chat_id'], unique=False)
    op.create_index('idx_emotion_confidence', 'emotions', ['confidence_score'], unique=False)
    op.create_index('idx_emotion_primary', 'emotions', ['primary_emotion'], unique=False)
    op.create_index('idx_emotion_sentiment', 'emotions', ['sentiment_score'], unique=False)
    op.create_index('idx_emotion_user_detected', 'emotions', ['user_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_emotions_chat_id'), 'emotions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_emotions_id'), 'emotions', ['id'], unique=False)
    op.create_index(op.f('ix_emotions_message_id'), 'emotions', ['message_id'], unique=False)
    op.create_index(op.f('ix_emotions_user_id'), 'emotions', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotions_user_id'), table_name='emotions')
    op.drop_index(op.f('ix_emotions_message_id'), table_name='emotions')
    op.drop_index(op.f('ix_emotions_id'), table_name='emotions')
    op.drop_index(op.f('ix_emotions_chat_id'), table_name='emotions')
    op.drop_index('idx_emotion_user_detected', table_name='emotions')
    op.drop_index('idx_emotion_sentiment', table_name='emotions')
    op.drop_index('idx_emotion_primary', table_name='emotions')
    op.drop_index('idx_emotion_confidence', table_name='emotions')
    op.drop_index('idx_emotion_chat', table_name='emotions')
    op.drop_table('emotions')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_content_hash'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index('idx_message_type', table_name='messages')
    op.drop_index('idx_message_sender_type', table_name='messages')
    op.drop_index('idx_message_hash', table_name='messages')
    op.drop_index('idx_message_flagged', table_name='messages')
    op.drop_index('idx_message_emotion', table_name='messages')
    op.drop_index('idx_message_deleted', table_name='messages')
    op.drop_index('idx_message_chat_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_index('idx_user_preference_updated', table_name='user_preferences')
    op.drop_index('idx_user_preference_interaction', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_related_topic'), table_name='chats')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_index('idx_chat_user_created', table_name='chats')
    op.drop_index('idx_chat_user_active', table_name='chats')
    op.drop_index('idx_chat_session', table_name='chats')
    op.drop_index('idx_chat_last_message', table_name='chats')
    op.drop_index('idx_chat_favorite', table_name='chats')
    op.drop_index('idx_chat_deleted', table_name='chats')
    op.drop_index('idx_chat_archived', table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_verification', table_name='users')
    op.drop_index('idx_user_username_active', table_name='users')
    op.drop_index('idx_user_reset_token', table_name='users')
    op.drop_index('idx_user_last_activity', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
